/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ExecutorsRouteImport } from './routes/executors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScriptsIndexRouteImport } from './routes/scripts.index'
import { Route as ScriptsSlugRouteImport } from './routes/scripts.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'

const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutorsRoute = ExecutorsRouteImport.update({
  id: '/executors',
  path: '/executors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsSlugRoute = ScriptsSlugRouteImport.update({
  id: '/scripts/$slug',
  path: '/scripts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/executors': typeof ExecutorsRoute
  '/premium': typeof PremiumRoute
  '/orders/$id': typeof OrdersIdRoute
  '/scripts/$slug': typeof ScriptsSlugRoute
  '/scripts/': typeof ScriptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/executors': typeof ExecutorsRoute
  '/premium': typeof PremiumRoute
  '/orders/$id': typeof OrdersIdRoute
  '/scripts/$slug': typeof ScriptsSlugRoute
  '/scripts': typeof ScriptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/executors': typeof ExecutorsRoute
  '/premium': typeof PremiumRoute
  '/orders/$id': typeof OrdersIdRoute
  '/scripts/$slug': typeof ScriptsSlugRoute
  '/scripts/': typeof ScriptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/executors'
    | '/premium'
    | '/orders/$id'
    | '/scripts/$slug'
    | '/scripts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/executors'
    | '/premium'
    | '/orders/$id'
    | '/scripts/$slug'
    | '/scripts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/executors'
    | '/premium'
    | '/orders/$id'
    | '/scripts/$slug'
    | '/scripts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExecutorsRoute: typeof ExecutorsRoute
  PremiumRoute: typeof PremiumRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ScriptsSlugRoute: typeof ScriptsSlugRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executors': {
      id: '/executors'
      path: '/executors'
      fullPath: '/executors'
      preLoaderRoute: typeof ExecutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$slug': {
      id: '/scripts/$slug'
      path: '/scripts/$slug'
      fullPath: '/scripts/$slug'
      preLoaderRoute: typeof ScriptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExecutorsRoute: ExecutorsRoute,
  PremiumRoute: PremiumRoute,
  OrdersIdRoute: OrdersIdRoute,
  ScriptsSlugRoute: ScriptsSlugRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
