/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SellRouteImport } from './routes/sell'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PointsRouteImport } from './routes/points'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as ExecutorsRouteImport } from './routes/executors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BuxPassRouteImport } from './routes/bux-pass'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScriptsIndexRouteImport } from './routes/scripts.index'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as ScriptsSlugRouteImport } from './routes/scripts.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as MarketSlugRouteImport } from './routes/market.$slug'
import { Route as ExecutorsSlugRouteImport } from './routes/executors.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as MarketOrdersIdRouteImport } from './routes/market.orders.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutorsRoute = ExecutorsRouteImport.update({
  id: '/executors',
  path: '/executors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuxPassRoute = BuxPassRouteImport.update({
  id: '/bux-pass',
  path: '/bux-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsSlugRoute = ScriptsSlugRouteImport.update({
  id: '/scripts/$slug',
  path: '/scripts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSlugRoute = MarketSlugRouteImport.update({
  id: '/market/$slug',
  path: '/market/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutorsSlugRoute = ExecutorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExecutorsRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const MarketOrdersIdRoute = MarketOrdersIdRouteImport.update({
  id: '/market/orders/$id',
  path: '/market/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bux-pass': typeof BuxPassRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/executors': typeof ExecutorsRouteWithChildren
  '/kyc': typeof KycRoute
  '/points': typeof PointsRoute
  '/premium': typeof PremiumRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
  '/wallet': typeof WalletRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/executors/$slug': typeof ExecutorsSlugRoute
  '/market/$slug': typeof MarketSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/scripts/$slug': typeof ScriptsSlugRoute
  '/market/': typeof MarketIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/market/orders/$id': typeof MarketOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bux-pass': typeof BuxPassRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/executors': typeof ExecutorsRouteWithChildren
  '/kyc': typeof KycRoute
  '/points': typeof PointsRoute
  '/premium': typeof PremiumRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
  '/wallet': typeof WalletRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/executors/$slug': typeof ExecutorsSlugRoute
  '/market/$slug': typeof MarketSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/scripts/$slug': typeof ScriptsSlugRoute
  '/market': typeof MarketIndexRoute
  '/scripts': typeof ScriptsIndexRoute
  '/market/orders/$id': typeof MarketOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bux-pass': typeof BuxPassRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/executors': typeof ExecutorsRouteWithChildren
  '/kyc': typeof KycRoute
  '/points': typeof PointsRoute
  '/premium': typeof PremiumRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
  '/wallet': typeof WalletRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/executors/$slug': typeof ExecutorsSlugRoute
  '/market/$slug': typeof MarketSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/scripts/$slug': typeof ScriptsSlugRoute
  '/market/': typeof MarketIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/market/orders/$id': typeof MarketOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bux-pass'
    | '/checkout'
    | '/community'
    | '/dashboard'
    | '/executors'
    | '/kyc'
    | '/points'
    | '/premium'
    | '/sell'
    | '/shop'
    | '/support'
    | '/tickets'
    | '/wallet'
    | '/checkout/success'
    | '/executors/$slug'
    | '/market/$slug'
    | '/orders/$id'
    | '/scripts/$slug'
    | '/market/'
    | '/scripts/'
    | '/market/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/bux-pass'
    | '/checkout'
    | '/community'
    | '/dashboard'
    | '/executors'
    | '/kyc'
    | '/points'
    | '/premium'
    | '/sell'
    | '/shop'
    | '/support'
    | '/tickets'
    | '/wallet'
    | '/checkout/success'
    | '/executors/$slug'
    | '/market/$slug'
    | '/orders/$id'
    | '/scripts/$slug'
    | '/market'
    | '/scripts'
    | '/market/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bux-pass'
    | '/checkout'
    | '/community'
    | '/dashboard'
    | '/executors'
    | '/kyc'
    | '/points'
    | '/premium'
    | '/sell'
    | '/shop'
    | '/support'
    | '/tickets'
    | '/wallet'
    | '/checkout/success'
    | '/executors/$slug'
    | '/market/$slug'
    | '/orders/$id'
    | '/scripts/$slug'
    | '/market/'
    | '/scripts/'
    | '/market/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BuxPassRoute: typeof BuxPassRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  ExecutorsRoute: typeof ExecutorsRouteWithChildren
  KycRoute: typeof KycRoute
  PointsRoute: typeof PointsRoute
  PremiumRoute: typeof PremiumRoute
  SellRoute: typeof SellRoute
  ShopRoute: typeof ShopRoute
  SupportRoute: typeof SupportRoute
  TicketsRoute: typeof TicketsRoute
  WalletRoute: typeof WalletRoute
  MarketSlugRoute: typeof MarketSlugRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ScriptsSlugRoute: typeof ScriptsSlugRoute
  MarketIndexRoute: typeof MarketIndexRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
  MarketOrdersIdRoute: typeof MarketOrdersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executors': {
      id: '/executors'
      path: '/executors'
      fullPath: '/executors'
      preLoaderRoute: typeof ExecutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bux-pass': {
      id: '/bux-pass'
      path: '/bux-pass'
      fullPath: '/bux-pass'
      preLoaderRoute: typeof BuxPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$slug': {
      id: '/scripts/$slug'
      path: '/scripts/$slug'
      fullPath: '/scripts/$slug'
      preLoaderRoute: typeof ScriptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$slug': {
      id: '/market/$slug'
      path: '/market/$slug'
      fullPath: '/market/$slug'
      preLoaderRoute: typeof MarketSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executors/$slug': {
      id: '/executors/$slug'
      path: '/$slug'
      fullPath: '/executors/$slug'
      preLoaderRoute: typeof ExecutorsSlugRouteImport
      parentRoute: typeof ExecutorsRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/market/orders/$id': {
      id: '/market/orders/$id'
      path: '/market/orders/$id'
      fullPath: '/market/orders/$id'
      preLoaderRoute: typeof MarketOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ExecutorsRouteChildren {
  ExecutorsSlugRoute: typeof ExecutorsSlugRoute
}

const ExecutorsRouteChildren: ExecutorsRouteChildren = {
  ExecutorsSlugRoute: ExecutorsSlugRoute,
}

const ExecutorsRouteWithChildren = ExecutorsRoute._addFileChildren(
  ExecutorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BuxPassRoute: BuxPassRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  ExecutorsRoute: ExecutorsRouteWithChildren,
  KycRoute: KycRoute,
  PointsRoute: PointsRoute,
  PremiumRoute: PremiumRoute,
  SellRoute: SellRoute,
  ShopRoute: ShopRoute,
  SupportRoute: SupportRoute,
  TicketsRoute: TicketsRoute,
  WalletRoute: WalletRoute,
  MarketSlugRoute: MarketSlugRoute,
  OrdersIdRoute: OrdersIdRoute,
  ScriptsSlugRoute: ScriptsSlugRoute,
  MarketIndexRoute: MarketIndexRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
  MarketOrdersIdRoute: MarketOrdersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
